CREATE TABLE credit
(
    id_credit             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    credit_code           UUID                                    NOT NULL,
    credit_value          DECIMAL                                 NOT NULL,
    day_first_installment date                                    NOT NULL,
    number_of_intallments INT                                     NOT NULL,
    status                INT,
    id_customer           BIGINT,
    CONSTRAINT pk_credit PRIMARY KEY (id_credit)
);

ALTER TABLE credit
    ADD CONSTRAINT uc_credit_creditcode UNIQUE (credit_code);

ALTER TABLE credit
    ADD CONSTRAINT FK_CREDIT_ON_ID_CUSTOMER FOREIGN KEY (id_customer) REFERENCES customer (id_customer);